/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface createInteraction {
  body: {
    description: string;
    name: string;
    request: {
      method: string;
      params?: {
        /**
         * Unknown Property
         */
        [x: string]: unknown;
      };
      query?: {
        /**
         * Unknown Property
         */
        [x: string]: unknown;
      };
      url: string;
    };
  };
  query?: {
    name?: string;
  };
}

export interface deleteInteraction {
  query: {
    name: string;
  };
}

export interface getInteraction {
  query: {
    name: string;
  };
}

export interface getInteractions {
  query: {
    name?: string;
  };
}

export interface updateInteraction {
  body: {
    description?: string;
    name?: string;
    request?: {
      method: string;
      params?: {
        /**
         * Unknown Property
         */
        [x: string]: unknown;
      };
      query?: {
        /**
         * Unknown Property
         */
        [x: string]: unknown;
      };
      url: string;
    };
  };
  query: {
    name: string;
  };
}
